name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg install sfml
          .\vcpkg\vcpkg integrate install

      - name: Configure with CMake
        run: |
          cmake -Bbuild "-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build project
        run: |
          cmake --build build --parallel --config Release