name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg install sfml[core,graphics,window]
          .\vcpkg\vcpkg integrate install

      - name: Configure with CMake
        run: |
          cmake -Bbuild "-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX=install

      - name: Build project
        run: |
          cmake --build build --parallel --config Release

      - name: Install project
        run: |
          cmake --install build --config Release

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path install\* -DestinationPath dokkan-battle-orb-system-win32.zip

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dokkan-battle-orb-system-win32.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}